let a = +prompt("Enter a :")
let b = +prompt("Enter b :")
plus=Math.abs (a)+ Math.abs (b)
minus=Math.abs (a)- Math.abs (b)
multiple=(a*b)
squareA=(a**2)
squareB=(b**2)
alert(`plus = ${plus}\n
       minus = ${minus}\n
       multiple = ${multiple}\n
       squareA = ${squareA}\n
       squareB = ${squareB}`)